app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/* -----------------------------------------------*/

/* Rutas Tipo resource*/
Route::resource('register','usuariosController');
Route::resource('login', 'loginController');
Route::get('logout',[
	'uses' => 'loginController@logout',
	'as'   => 'logout'
]);


Route::group(['middleware' => 'auth'], function () {
	Route::get('/',[
		'uses'	=> 'homeController@index',
		'as'	=> 'index'
		]);
	Route::resource('noticias','noticiasController');
	Route::get('noticias/{id}/destroy',[
      'uses' => 'noticiasController@destroy',
      'as'   => 'noticias.destroy'
    ]);
    Route::get('noticias/{id}/ver',[
      'uses' => 'noticiasController@ver',
      'as'   => 'noticias.ver'
    ]);
    
	Route::resource('categorias','categoriasController');
    
    Route::resource('preguntas','preguntasController');
    Route::get('preguntas/{id}/destroy',[
      'uses' => 'preguntasController@destroy',
      'as'   => 'preguntas.destroy'
    ]);
     Route::get('preguntas/{id}/ver',[
      'uses' => 'preguntasController@ver',
      'as'   => 'preguntas.ver'
    ]);
    
    
    Route::resource('guias','guiasController');
    Route::get('guias/{id}/destroy',[
      'uses' => 'guiasController@destroy',
      'as'   => 'guias.destroy'
    ]);
      Route::get('guias/{id}/ver',[
      'uses' => 'guiasController@ver',
      'as'   => 'guias.ver'
    ]);
    
    
    Route::resource('ejercicios','ejerciciosController');
     Route::get('ejercicios/{id}/destroy',[
      'uses' => 'ejerciciosController@destroy',
      'as'   => 'ejercicios.destroy'
    ]);
     Route::get('ejercicios/{id}/ver',[
      'uses' => 'ejerciciosController@ver',
      'as'   => 'ejercicios.ver'
    ]);
    Route::resource('comentarios','comentariosController');

    Route::group(['prefix'=>'perfil', 'middleware' => 'auth'], function () {
      Route::get('/',[
        'uses' => 'perfilController@index',
        'as'   => 'perfil.index'
      ]);
      
      Route::resource('foto','fotoPerfilController');
    });
});



/* -----------------------------------------------*/

resources/views/vistas/ejercicios.blade.php
<?php $data = \App\Ejercicio::orderBy('created_at', 'desc')->paginate(20); ?>
@foreach($data as $dato)
	@if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
	
	@endif
	
	<div style="border-radius:3px;"  class="ui segment ">
		<h3 class="ui header paginacion">
            <a style="color: #2c3e50; text-decoration: none;" href="{{route('ejercicios.ver',$dato->id)}}">{{ $dato->titulo }}</a>
            @if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
				<div style="float: right;" class="ui dropdown">
				  	<i  style="color: #6BC0E9;" class="setting icon"></i>
				  	<div class="menu">
					    <a class="item" href="{{route('ejercicios.edit', $dato->id)}}"> Editar</a>
					    <a class="item" href="{{route('ejercicios.destroy', $dato->id)}}"> Borrar</a>
					</div>
				</div>
			@endif
		</h3>
		<i class="ui user icon"></i>{{ $dato->autor }}| <i class="ui calendar outline icon"></i>{!!date('d/m', strtotime($dato->created_at))!!} del {!!date('Y', strtotime($dato->created_at))!!} | <i class="ui wait icon"></i>{!!date('H:i', strtotime($dato->created_at))!!} | <i class="ui icon signal"></i> {{ $dato->dificultad }}
	</div>
@endforeach

resources/views/vistas/guias.blade.php
<?php $data = \App\Guia::orderBy('created_at', 'desc')->paginate(20); ?>
@foreach($data as $dato)
	@if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
	@endif
	
	<div style="border-radius:3px;"  class="ui segment ">
		<h3 class="ui header paginacion" style="padding-bottom: 1em;">
            <a style="color: #2c3e50; text-decoration: none;" href="{{route('guias.ver',$dato->id)}}">{{ $dato->titulo }}</a>

            @if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
				<div style="float: right;"class="ui dropdown">
				  	<i  style="" class="setting icon"></i>
				  	<div class="menu">
					    <a class="item" href="{{route('guias.edit', $dato->id)}}"> Editar</a>
					    <a class="item" href="{{route('guias.destroy', $dato->id)}}"> Borrar</a>
					</div>
				</div>
			@endif
		</h3>
		<i class="ui user icon"></i>{{ $dato->autor }}| <i class="ui calendar outline icon"></i>{!!date('d/m', strtotime($dato->created_at))!!} del {!!date('Y', strtotime($dato->created_at))!!} | <i class="ui wait icon"></i>{!!date('H:i', strtotime($dato->created_at))!!} | <i class="ui icon list layout"></i> {{ $dato->categoria }}
	</div>
@endforeach

resources/views/vistas/preguntas.blade.php
<?php $data = \App\Pregunta::orderBy('created_at', 'desc')->paginate(20); ?>
	@foreach($data as $dato)
	@if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
	
	@endif
	
	<div style="border-radius:3px;"  class="ui  segment border-card p-top-lg p-bottom-lg shadow-bottom">
		<h3 class="ui header paginacion">
			<?php $foto = \App\User::where('username', $dato->autor)->first(); ?>
			<img class="ui top aligned tiny circular image img-section-for" style="width: 32px; height: 32px;" src="{!!asset('img/perfil/'.$foto->foto)!!}">
            <a style="color: #2c3e50; text-decoration: none;" href="{{route('preguntas.ver',$dato->id)}}">{{ $dato->titulo }}</a>

            @if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
				<div style ="float: right;" class="ui dropdown">
				  	<i  style="color: #6BC0E9;" class="setting icon"></i>
				  	<div class="menu">
					    <a class="item" href="{{route('preguntas.edit', $dato->id)}}"> Editar</a>
					    <a class="item" href="{{route('preguntas.destroy', $dato->id)}}"> Borrar</a>
					</div>
				</div>
			@endif
		</h3>
		<i class="ui user icon"></i>{{ $dato->autor }} | <i class="ui calendar outline icon"></i>{!!date('d/m', strtotime($dato->created_at))!!} del {!!date('Y', strtotime($dato->created_at))!!} | <i class="ui wait icon"></i>{!!date('H:i', strtotime($dato->created_at))!!}
	</div>
@endforeach