app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/* -----------------------------------------------*/

/* Rutas Tipo resource*/
Route::resource('register','usuariosController');
Route::resource('login', 'loginController');
Route::get('logout',[
	'uses' => 'loginController@logout',
	'as'   => 'logout'
]);


Route::group(['middleware' => 'auth'], function () {
	Route::get('/',[
		'uses'	=> 'homeController@index',
		'as'	=> 'index'
		]);
	Route::resource('noticias','noticiasController');
	Route::get('noticias/{id}/destroy',[
      'uses' => 'noticiasController@destroy',
      'as'   => 'noticias.destroy'
    ]);
    Route::get('noticias/{id}/ver',[
      'uses' => 'noticiasController@ver',
      'as'   => 'noticias.ver'
    ]);
    
	Route::resource('categorias','categoriasController');
    
    Route::resource('preguntas','preguntasController');
    Route::get('preguntas/{id}/destroy',[
      'uses' => 'preguntasController@destroy',
      'as'   => 'preguntas.destroy'
    ]);
     Route::get('preguntas/{id}/ver',[
      'uses' => 'preguntasController@ver',
      'as'   => 'preguntas.ver'
    ]);
    
    
    Route::resource('guias','guiasController');
    Route::get('guias/{id}/destroy',[
      'uses' => 'guiasController@destroy',
      'as'   => 'guias.destroy'
    ]);
      Route::get('guias/{id}/ver',[
      'uses' => 'guiasController@ver',
      'as'   => 'guias.ver'
    ]);
    
    
    Route::resource('ejercicios','ejerciciosController');
     Route::get('ejercicios/{id}/destroy',[
      'uses' => 'ejerciciosController@destroy',
      'as'   => 'ejercicios.destroy'
    ]);
     Route::get('ejercicios/{id}/ver',[
      'uses' => 'ejerciciosController@ver',
      'as'   => 'ejercicios.ver'
    ]);
    Route::resource('comentarios','comentariosController');

    Route::group(['prefix'=>'perfil', 'middleware' => 'auth'], function () {
      Route::get('/',[
        'uses' => 'perfilController@index',
        'as'   => 'perfil.index'
      ]);
      
      Route::resource('foto','fotoPerfilController');
    });
});



/* -----------------------------------------------*/

app/Noticia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Noticia extends Model
{
    protected $table = 'noticias';
    protected $fillable = ['titulo','contenido','autor','categoria', 'imagen'];
}

app/Http/Controllers/noticiasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use \App\Noticia;
class noticiasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$data = \App\Noticia::orderBy('created_at', 'desc')->paginate(20);
        return view('index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         $categoria = \App\Categoria::orderBy('nombre', 'desc')->get();
         return view('noticias.create',compact('categoria'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $file = $request->file('imagen');
        $foto = Auth::user()->username.'.'.$file->getClientOriginalExtension();
        $file->move(public_path().'/img/noticias', $foto);

        \App\Noticia::create([
			'titulo'=>$request['titulo'],
			'contenido'=>$request['contenido'],
            'autor' => Auth::user()->username,
            'categoria'=>$request['categoria'],
            'imagen' => $foto
		]);
		return redirect()->route('index');
    }

    public function ver($id)
    {
        $not = \App\Noticia::find($id);
        return view('noticias.ver',compact('not'));
    }

    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Noticia::find($id);
        $categoria = \App\Categoria::orderBy('nombre', 'desc')->get();
        return view('noticias.edit', compact('data', 'categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $noticia = \App\Noticia::find($id);
        $noticia-> fill([
            'titulo'=>$request['titulo'],
            'contenido'=>$request['contenido'],
            'autor' => Auth::user()->username,
            'categoria'=>$request['categoria'],
        ])->save();
        return redirect()->route('index');
    }
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Noticia::destroy($id);
        return back();
    }
}

resources/views/noticias/create.blade.php
@extends('layouts.template')
@section('content')
<div class="container ui">
		<div class="ui grid">
			<div class="three column row">	
				<!-- Perfil de Usuario -->
				<div class="column three wide">
					@include('secciones.perfil')
				<!-- Ultimas Preguntas-->
				    @include('secciones.preguntas')
				</div>
				
				<div class="nine wide column ">
				<h2 class="ui header paginacion">
					Nueva noticia
				</h2>	
				{!!Form::open(['route'=>'noticias.store','method'=>'POST', 'class'=>'ui form ingresar', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
					<div  class="ui raised segment ">	
						<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
						<div class="ui">
							<h2 class="ui header">
								{!!Form::text('titulo', null,['placeholder'=>'Titulo de la nueva noticia', 'style'=>'font-size:16px;color:#484848;'])!!}
							</h2>
						</div>
					</div>
					<i class="ui user icon"></i>{{ Auth::user()->username }}| <i class="ui calendar outline icon"></i>{{ date('d/m/Y') }} | <i class="ui wait icon"></i>{{ date('H:i')}}
					<div  class="ui raised segment ">
						<div class="ui">
							{!!Form::textarea('contenido', null,['placeholder'=>'Contenido de tu noticia... Ejemp:Lorem ipsum dolor sit amet...', 'style'=>'border: none; border-radius: none; background: none; font-size:14px; padding-left: none;margin-left: none;','id'=>'editor'])!!}
						</div>
					</div>
				</div>
				<div  class="four wide column">
					<!-- Publicar -->
					<div class="ui card">
						<div class="content">
							<div class="header"> <center> Publicar</center></div>
						</div>
						<div class="extra content">
							<button type="submit" class="ui primary submit button">Publicar</button>
						</div>
					</div>	
					<!-- Categoría -->
					<div class="ui card">
						<div class="content">
							<div class="header"> <center> Categoría</center></div>
						</div>
						<div class="content">
							@foreach($categoria as $categorias)
								<div class="ui radio checkbox">
									<input type="radio" checked name="categoria" id="{!!$categorias->id!!}" value="{!!$categorias->id!!}"> <label for="{!!$categorias->id!!}">{!!$categorias->nombre!!}</label>
								</div>
								<br><br>
							@endforeach
						</div>
						<div class="extra content">
							<div class="form-group">
								<a href="{{route('categorias.create')}}" class="fluid ui teal button">Añadir nuevas</a>
							</div>
						</div>
					</div>	
					<!-- Imagen -->
					<div class="ui card">
						<div class="content">
							<div class="header"> <center> Imagen destacada</center></div>
						</div>
						<div class="content">
							<input id="foto" type="file" name="imagen" onchange="readURL(this);" style="display: none;">
							<label for="foto">
								<img src="" id="prev" alt="" width="100%">
								<center>Añadir imagen destacada</center>
							</label>
						</div>
					</div>	
				</div>
			{!!Form::close()!!}
			</div>
		</div>
	</div>
@endsection
@section('js')
<script>
 $('select.dropdown')
  .dropdown()
;
function readURL(input) {
 if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
        $('#prev').attr('src', e.target.result);
     }
 
    reader.readAsDataURL(input.files[0]);
 }
}

</script>
@endsection

resources/views/noticias/edit.blade.php
@extends('layouts.template')
@section('content')
<div class="container ui">
		<div class="ui grid">
			<div class="three column row">	
				<!-- Perfil de Usuario -->
				<div class="column three wide">
					@include('secciones.perfil')
				<!-- Ultimas Preguntas-->
				    @include('secciones.preguntas')
				</div>
				<div class="nine wide column ">
				<h2 class="ui header paginacion">
					Nueva noticia
				</h2>		
						{!!Form::model($data, ['route'=>['noticias.update', $data->id],'method'=>'PUT', 'class'=>'ui form ingresar'])!!}
						<div  class="ui raised segment ">	
						<input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
						<div class="ui">
							<h2 class="ui header">
								{!!Form::text('titulo', null,['placeholder'=>'Titulo de la nueva noticia', 'style'=>'font-size:16px;color:#484848;'])!!}
							</h2>
						</div>
					</div>
					<i class="ui user icon"></i>{{ Auth::user()->username }}| <i class="ui calendar outline icon"></i>{{ date('d/m/Y') }} | <i class="ui wait icon"></i>{{ date('H:i')}}
					<div  class="ui raised segment ">
						<div class="ui">
							{!!Form::textarea('contenido', null,['placeholder'=>'Contenido de tu noticia... Ejemp:Lorem ipsum dolor sit amet...', 'style'=>'border: none; border-radius: none; background: none; font-size:14px; padding-left: none;margin-left: none;','id'=>'editor'])!!}
						</div>
					</div>
				</div>
				<div  class="four wide column">
					<!-- Publicar -->
					<div class="ui card">
						<div class="content">
							<div class="header"> <center> Publicar</center></div>
						</div>
						<div class="extra content">
							<button type="submit" class="ui primary submit button">Publicar</button>
						</div>
					</div>	
					<!-- Categoría -->
					<div class="ui card">
						<div class="content">
							<div class="header"> <center> Categoría</center></div>
						</div>
						<div class="content">
							@foreach($categoria as $categorias)
								<div class="ui radio checkbox">
									<input type="radio" checked name="categoria" id="{!!$categorias->id!!}" value="{!!$categorias->id!!}"> <label for="{!!$categorias->id!!}">{!!$categorias->nombre!!}</label>
								</div>
								<br><br>
							@endforeach
						</div>
						<div class="extra content">
							<div class="form-group">
								<a href="{{route('categorias.create')}}" class="fluid ui teal button">Añadir nuevas</a>
							</div>
						</div>
					</div>	
					<!-- Imagen -->
					<div class="ui card">
						<div class="content">
							<div class="header"> <center> Imagen destacada</center></div>
						</div>
						<div class="content">
							<input id="foto" type="file" name="imagen" onchange="readURL(this);" style="display: none;">
							<label for="foto">
								<img src="" id="prev" alt="" width="100%">
								<center>Añadir imagen destacada</center>
							</label>
						</div>
					</div>	
				</div>
			   {!!Form::close()!!}
			</div>
		</div>
	</div>
@endsection
@section('js')
<script>
 $('select.dropdown')
  .dropdown()
;
function readURL(input) {
 if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
        $('#prev').attr('src', e.target.result);
     }
 
    reader.readAsDataURL(input.files[0]);
 }
}

</script>
@endsection

resources/views/noticias/index.blade.php
@extends('layouts.template')
@section('content')
	<div class="container ui">
		<div class="ui grid">
			<div class="three column row">	
				<!-- Perfil de Usuario -->
				<div class="column three wide">
					@include('secciones.perfil')
				<!-- Ultimas Preguntas-->
				    @include('secciones.preguntas')
				</div>
				<div class="nine wide column ">
					<h2 class="ui header paginacion">Noticias</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua.</p>
						
					@foreach($data as $dato)
					@if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
						<a href="{{route('noticias.create')}}" class="fluid ui button orange">Publicar una noticia</a>
					@endif
					
					<div style="border-radius:3px;"  class="ui segment ">
						<h3 class="ui header paginacion">
				            <a style="color: #2c3e50; text-decoration: none;" href="{{route('noticias.ver',$dato->id)}}">{{ $dato->titulo }}</a>
				            @if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $dato->autor))
								<div style="float: right;" class="ui dropdown">
								  	<i  style="color: #76C4EA;" class="setting icon"></i>
								  	<div class="menu">
									    <a class="item" href="{{route('noticias.edit', $dato->id)}}"> Editar</a>
									    <a class="item" href="{{route('noticias.destroy', $dato->id)}}"> Borrar</a>
									</div>
								</div>
							@endif
						</h3>
						
						{!!substr($dato->contenido,0,255)!!}...
						<br><br>
						<i class="ui user icon"></i>{{ $dato->autor }}| <i class="ui calendar outline icon"></i>{!!date('d/m', strtotime($dato->created_at))!!} del {!!date('Y', strtotime($dato->created_at))!!} | <i class="ui wait icon"></i>{!!date('H:i', strtotime($dato->created_at))!!} | <i class="ui icon list layout"></i> {{ $dato->categoria }}
					</div>
					@endforeach
				</div>
				<div  class="four wide column">
					<!-- Ultimos ejercicios -->
					@include('secciones.ejercicios')	
				</div>
			</div>
		</div>
	</div>
@endsection
@section('js')

@endsection

resources/views/noticias/ver.blade.php
<?php
use App\Comentario;
$coment = \App\Comentario::where('idpublicacion',$not->id)->where('seccion','noticias')->get();
?>
@extends('layouts.template')
@section('header')
<link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">
@endsection
@section('content')
<div class="container ui">
		<div class="ui grid">
			<div class="three column row">	
				<!-- Perfil de Usuario -->
				<div class="column three wide">
					@include('secciones.perfil')
				<!-- Ultimas Preguntas-->
				    @include('secciones.preguntas')
				</div>
				<div class="thirteen wide column ">				
					<?php
						$autor = \App\User::where('username', $not->autor)->first();
					 ?>
					<div style="border-radius:0px; font-size: 16px; font-family: 'Lato', serif;color: black;" class="ui segment">
							@if((Auth::user()->tipo == '0') || (Auth::user()->tipo == '2') || (Auth::user()->tipo == '3') || (Auth::user()->username == $not->autor))
								<div style="float: right;" class="ui dropdown">
								  	<i class="setting icon"></i>
								  	<div class="menu">
									    <a class="item" href="{{route('noticias.edit', $not->id)}}"> Editar</a>
									    <a class="item" href="{{route('noticias.destroy', $not->id)}}"> Borrar</a>
									</div>
								</div>
							@endif
							<h2 class="ui header paginacion">
								<h2 class="ui header">
								  <img src="{{asset('/img/perfil/'.$autor->foto)}}" class="ui circular image">
								  	<a style="color: #2c3e50; text-decoration: none;" href="{{route('noticias.ver',$not->id)}}">
								  		{{ $not->titulo }} <br>
								  	</a>
								  <small>
								  	<sub>
								  		<i class="ui user icon"></i>{{ $not->autor }}| <i class="ui calendar outline icon"></i>{!!date('d/m', strtotime($not->created_at))!!} del {!!date('Y', strtotime($not->created_at))!!} | <i class="ui wait icon"></i>{!!date('H:i', strtotime($not->created_at))!!} | <i class="ui icon list layout"></i> {{ $not->categoria }}
								  	</sub>
								  </small>
								</h2>
						        <a style="color: #2c3e50; text-decoration: none;" href="{{route('noticias.ver',$not->id)}}">
									<img class="ui fluid image" src="{{asset('img/noticias/'.$not->imagen)}}" width="100%" alt="">
								</a>
						</h2>
						<?php
							$contenido = str_replace("&lt;", "<", $not->contenido);
							$contenido = str_replace("&gt;", ">", $contenido);
						?>
						<p>{!!$contenido!!}</p>	
						
						    
					</div>
					<div class="ui very padded segment">
				     <div class="ui comments" style="margin-left: auto; margin-right: auto;">
                      <h3 class="ui dividing header">Comentarios</h3>
                      @foreach($coment as $coments)
                      	<?php $user = \App\User::where('username', $coments->autor)->get(); ?>
                       <div class="comment">
                        <a class="avatar">
                        	@foreach($user as $us)
                          		<img src="{!!asset('img/perfil/'.$us->foto)!!}">
                          	@endforeach
                        </a>
                        <div class="content">
                          <a class="author">{!!$coments->autor!!}</a>
                          <div class="metadata">
                            <span class="date">{!!date('d/m', strtotime($coments->created_at))!!} del {!!date('Y', strtotime($coments->created_at))!!}</span>
                          </div>
                          <div class="text">
                            {!!$coments->comentario!!}
                          </div>
                        </div>
                      </div>
                      @endforeach
                      {!!Form::open(['route'=>'comentarios.store','method'=>'POST', 'class'=>'ui form ingresar', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
                        <div class="field">
                          {!!Form::textarea('comentario', null,['placeholder'=>'Aquí tu comentario'])!!}
                          {!!Form::hidden('seccion', 'noticias')!!}
                          {!!Form::hidden('idpublicacion', $not->id)!!}
                        </div>
                        <button class="ui blue labeled submit icon button"> <i class="icon edit"></i> Comentar</button>
                      {!!Form::close()!!}
                    </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
@endsection
@section('js')

@endsection